//
// This file is automatically generated by scripts/generate-plugins.go -- Do not edit!
//
package command

import (
	chefprovisioner "github.com/schiangtc/terraform/builtin/provisioners/chef"
	fileprovisioner "github.com/schiangtc/terraform/builtin/provisioners/file"
	habitatprovisioner "github.com/schiangtc/terraform/builtin/provisioners/habitat"
	localexecprovisioner "github.com/schiangtc/terraform/builtin/provisioners/local-exec"
	puppetprovisioner "github.com/schiangtc/terraform/builtin/provisioners/puppet"
	remoteexecprovisioner "github.com/schiangtc/terraform/builtin/provisioners/remote-exec"
	saltmasterlessprovisioner "github.com/schiangtc/terraform/builtin/provisioners/salt-masterless"

	"github.com/schiangtc/terraform/plugin"
)

var InternalProviders = map[string]plugin.ProviderFunc{}

var InternalProvisioners = map[string]plugin.ProvisionerFunc{
	"chef":            chefprovisioner.Provisioner,
	"file":            fileprovisioner.Provisioner,
	"habitat":         habitatprovisioner.Provisioner,
	"local-exec":      localexecprovisioner.Provisioner,
	"puppet":          puppetprovisioner.Provisioner,
	"remote-exec":     remoteexecprovisioner.Provisioner,
	"salt-masterless": saltmasterlessprovisioner.Provisioner,
}
